class Forth_UnderflowError(IndexError): ...


class Forth_EvaluationError(RuntimeError): ...


class Forth_CompilationError(SyntaxError): ...


class Forth_InvalidExpr(SyntaxError): ...


class Forth_NotFound(KeyError): ...


class Forth_NoWord(EOFError): ...


class Forth_HeaderRedefinitionError(RuntimeError): ...
