class Forth_UnderflowError(Exception): ...


class Forth_EvaluationError(Exception): ...


class Forth_CompilationError(Exception): ...


class Forth_InvalidExpr(Exception): ...


class Forth_NotFound(Exception): ...


class Forth_NoWord(Exception): ...


class Forth_HeaderRedefinitionError(Exception): ...


class Forth_NotImplemented(Exception): ...
