class Forth_Runtime_UnderflowError(Exception): ...


class Forth_Runtime_EvaluationError(Exception): ...


class Forth_Runtime_WordNotFoundError(Exception): ...


class Forth_Runtime_HeaderRedefinitionError(Exception): ...


class Forth_Runtime_NotImplementedError(Exception): ...


class Forth_Runtime_UnexpectedEOFError(Exception): ...
